"""create domain schema

Revision ID: 0001
Revises:
Create Date: 2026-05-17

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("customer_name", sa.String(length=160), nullable=False),
        sa.Column("customer_type", sa.String(length=40), nullable=False),
        sa.Column("credit_terms_days", sa.Integer(), nullable=False),
        sa.Column("primary_freight_type", sa.String(length=60), nullable=False),
        sa.Column("account_status", sa.String(length=20), nullable=False),
        sa.Column("contract_start_date", sa.Date(), nullable=False),
        sa.Column("annual_revenue_potential", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("customer_id"),
    )
    op.create_table(
        "drivers",
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column("termination_date", sa.Date(), nullable=True),
        sa.Column("license_number", sa.String(length=40), nullable=False),
        sa.Column("license_state", sa.String(length=2), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("home_terminal", sa.String(length=80), nullable=False),
        sa.Column("employment_status", sa.String(length=20), nullable=False),
        sa.Column("cdl_class", sa.String(length=2), nullable=False),
        sa.Column("years_experience", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("driver_id"),
    )
    op.create_index("ix_drivers_employment_status", "drivers", ["employment_status"], unique=False)
    op.create_table(
        "facilities",
        sa.Column("facility_id", sa.Integer(), nullable=False),
        sa.Column("facility_name", sa.String(length=160), nullable=False),
        sa.Column("facility_type", sa.String(length=40), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("dock_doors", sa.Integer(), nullable=False),
        sa.Column("operating_hours", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("facility_id"),
    )
    op.create_table(
        "routes",
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("origin_city", sa.String(length=80), nullable=False),
        sa.Column("origin_state", sa.String(length=2), nullable=False),
        sa.Column("destination_city", sa.String(length=80), nullable=False),
        sa.Column("destination_state", sa.String(length=2), nullable=False),
        sa.Column("typical_distance_miles", sa.Integer(), nullable=False),
        sa.Column("base_rate_per_mile", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("fuel_surcharge_rate", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("typical_transit_days", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("route_id"),
    )
    op.create_table(
        "trailers",
        sa.Column("trailer_id", sa.Integer(), nullable=False),
        sa.Column("trailer_number", sa.String(length=20), nullable=False),
        sa.Column("trailer_type", sa.String(length=40), nullable=False),
        sa.Column("length_feet", sa.Integer(), nullable=False),
        sa.Column("model_year", sa.Integer(), nullable=False),
        sa.Column("vin", sa.String(length=20), nullable=False),
        sa.Column("acquisition_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_location", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("trailer_id"),
        sa.UniqueConstraint("trailer_number"),
        sa.UniqueConstraint("vin"),
    )
    op.create_index("ix_trailers_status", "trailers", ["status"], unique=False)
    op.create_table(
        "trucks",
        sa.Column("truck_id", sa.Integer(), nullable=False),
        sa.Column("unit_number", sa.String(length=20), nullable=False),
        sa.Column("make", sa.String(length=60), nullable=False),
        sa.Column("model_year", sa.Integer(), nullable=False),
        sa.Column("vin", sa.String(length=20), nullable=False),
        sa.Column("acquisition_date", sa.Date(), nullable=False),
        sa.Column("acquisition_mileage", sa.Integer(), nullable=False),
        sa.Column("fuel_type", sa.String(length=20), nullable=False),
        sa.Column("tank_capacity_gallons", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("home_terminal", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("truck_id"),
        sa.UniqueConstraint("unit_number"),
        sa.UniqueConstraint("vin"),
    )
    op.create_index("ix_trucks_status", "trucks", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table(
        "driver_monthly_metrics",
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("trips_completed", sa.Integer(), nullable=False),
        sa.Column("total_miles", sa.Integer(), nullable=False),
        sa.Column("total_revenue", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("average_mpg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("total_fuel_gallons", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("on_time_delivery_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("average_idle_hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.driver_id"],
        ),
        sa.PrimaryKeyConstraint("driver_id", "month", name="pk_driver_monthly_metrics"),
    )
    op.create_table(
        "loads",
        sa.Column("load_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("load_date", sa.Date(), nullable=False),
        sa.Column("load_type", sa.String(length=40), nullable=False),
        sa.Column("weight_lbs", sa.Integer(), nullable=False),
        sa.Column("pieces", sa.Integer(), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("fuel_surcharge", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("accessorial_charges", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("load_status", sa.String(length=20), nullable=False),
        sa.Column("booking_type", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.route_id"],
        ),
        sa.PrimaryKeyConstraint("load_id"),
    )
    op.create_index(op.f("ix_loads_customer_id"), "loads", ["customer_id"], unique=False)
    op.create_index("ix_loads_load_date", "loads", ["load_date"], unique=False)
    op.create_index("ix_loads_load_status", "loads", ["load_status"], unique=False)
    op.create_index(op.f("ix_loads_route_id"), "loads", ["route_id"], unique=False)
    op.create_table(
        "maintenance_records",
        sa.Column("maintenance_id", sa.Integer(), nullable=False),
        sa.Column("truck_id", sa.Integer(), nullable=False),
        sa.Column("maintenance_date", sa.Date(), nullable=False),
        sa.Column("maintenance_type", sa.String(length=60), nullable=False),
        sa.Column("odometer_reading", sa.Integer(), nullable=False),
        sa.Column("labor_hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("labor_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("parts_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("facility_location", sa.String(length=120), nullable=False),
        sa.Column("downtime_hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("service_description", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["truck_id"],
            ["trucks.truck_id"],
        ),
        sa.PrimaryKeyConstraint("maintenance_id"),
    )
    op.create_index(
        op.f("ix_maintenance_records_truck_id"), "maintenance_records", ["truck_id"], unique=False
    )
    op.create_table(
        "truck_utilization_metrics",
        sa.Column("truck_id", sa.Integer(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("trips_completed", sa.Integer(), nullable=False),
        sa.Column("total_miles", sa.Integer(), nullable=False),
        sa.Column("total_revenue", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("average_mpg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("maintenance_events", sa.Integer(), nullable=False),
        sa.Column("maintenance_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("downtime_hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("utilization_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["truck_id"],
            ["trucks.truck_id"],
        ),
        sa.PrimaryKeyConstraint("truck_id", "month", name="pk_truck_utilization_metrics"),
    )
    op.create_table(
        "trips",
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("load_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("truck_id", sa.Integer(), nullable=False),
        sa.Column("trailer_id", sa.Integer(), nullable=False),
        sa.Column("dispatch_date", sa.Date(), nullable=False),
        sa.Column("actual_distance_miles", sa.Integer(), nullable=False),
        sa.Column("actual_duration_hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("fuel_gallons_used", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("average_mpg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("idle_time_hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("trip_status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.driver_id"],
        ),
        sa.ForeignKeyConstraint(
            ["load_id"],
            ["loads.load_id"],
        ),
        sa.ForeignKeyConstraint(
            ["trailer_id"],
            ["trailers.trailer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["truck_id"],
            ["trucks.truck_id"],
        ),
        sa.PrimaryKeyConstraint("trip_id"),
        sa.UniqueConstraint("load_id", name="uq_trips_load_id"),
    )
    op.create_index(op.f("ix_trips_driver_id"), "trips", ["driver_id"], unique=False)
    op.create_index(op.f("ix_trips_load_id"), "trips", ["load_id"], unique=False)
    op.create_index(op.f("ix_trips_trailer_id"), "trips", ["trailer_id"], unique=False)
    op.create_index("ix_trips_trip_status", "trips", ["trip_status"], unique=False)
    op.create_index(op.f("ix_trips_truck_id"), "trips", ["truck_id"], unique=False)
    op.create_table(
        "delivery_events",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("load_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("facility_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_datetime", sa.DateTime(), nullable=False),
        sa.Column("actual_datetime", sa.DateTime(), nullable=False),
        sa.Column("detention_minutes", sa.Integer(), nullable=False),
        sa.Column("on_time_flag", sa.Boolean(), nullable=False),
        sa.Column("location_city", sa.String(length=80), nullable=False),
        sa.Column("location_state", sa.String(length=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.facility_id"],
        ),
        sa.ForeignKeyConstraint(
            ["load_id"],
            ["loads.load_id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.trip_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_delivery_events_event_type", "delivery_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_events_facility_id"), "delivery_events", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_events_load_id"), "delivery_events", ["load_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_events_trip_id"), "delivery_events", ["trip_id"], unique=False
    )
    op.create_table(
        "fuel_purchases",
        sa.Column("fuel_purchase_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("truck_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("location_city", sa.String(length=80), nullable=False),
        sa.Column("location_state", sa.String(length=2), nullable=False),
        sa.Column("gallons", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("price_per_gallon", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("fuel_card_number", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.driver_id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.trip_id"],
        ),
        sa.ForeignKeyConstraint(
            ["truck_id"],
            ["trucks.truck_id"],
        ),
        sa.PrimaryKeyConstraint("fuel_purchase_id"),
    )
    op.create_index(
        op.f("ix_fuel_purchases_driver_id"), "fuel_purchases", ["driver_id"], unique=False
    )
    op.create_index(
        "ix_fuel_purchases_purchase_date", "fuel_purchases", ["purchase_date"], unique=False
    )
    op.create_index(op.f("ix_fuel_purchases_trip_id"), "fuel_purchases", ["trip_id"], unique=False)
    op.create_index(
        op.f("ix_fuel_purchases_truck_id"), "fuel_purchases", ["truck_id"], unique=False
    )
    op.create_table(
        "safety_incidents",
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("truck_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("incident_date", sa.Date(), nullable=False),
        sa.Column("incident_type", sa.String(length=60), nullable=False),
        sa.Column("location_city", sa.String(length=80), nullable=False),
        sa.Column("location_state", sa.String(length=2), nullable=False),
        sa.Column("at_fault_flag", sa.Boolean(), nullable=False),
        sa.Column("injury_flag", sa.Boolean(), nullable=False),
        sa.Column("vehicle_damage_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cargo_damage_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("claim_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("preventable_flag", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.driver_id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.trip_id"],
        ),
        sa.ForeignKeyConstraint(
            ["truck_id"],
            ["trucks.truck_id"],
        ),
        sa.PrimaryKeyConstraint("incident_id"),
    )
    op.create_index(
        op.f("ix_safety_incidents_driver_id"), "safety_incidents", ["driver_id"], unique=False
    )
    op.create_index(
        op.f("ix_safety_incidents_trip_id"), "safety_incidents", ["trip_id"], unique=False
    )
    op.create_index(
        op.f("ix_safety_incidents_truck_id"), "safety_incidents", ["truck_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_safety_incidents_truck_id"), table_name="safety_incidents")
    op.drop_index(op.f("ix_safety_incidents_trip_id"), table_name="safety_incidents")
    op.drop_index(op.f("ix_safety_incidents_driver_id"), table_name="safety_incidents")
    op.drop_table("safety_incidents")
    op.drop_index(op.f("ix_fuel_purchases_truck_id"), table_name="fuel_purchases")
    op.drop_index(op.f("ix_fuel_purchases_trip_id"), table_name="fuel_purchases")
    op.drop_index("ix_fuel_purchases_purchase_date", table_name="fuel_purchases")
    op.drop_index(op.f("ix_fuel_purchases_driver_id"), table_name="fuel_purchases")
    op.drop_table("fuel_purchases")
    op.drop_index(op.f("ix_delivery_events_trip_id"), table_name="delivery_events")
    op.drop_index(op.f("ix_delivery_events_load_id"), table_name="delivery_events")
    op.drop_index(op.f("ix_delivery_events_facility_id"), table_name="delivery_events")
    op.drop_index("ix_delivery_events_event_type", table_name="delivery_events")
    op.drop_table("delivery_events")
    op.drop_index(op.f("ix_trips_truck_id"), table_name="trips")
    op.drop_index("ix_trips_trip_status", table_name="trips")
    op.drop_index(op.f("ix_trips_trailer_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_load_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_driver_id"), table_name="trips")
    op.drop_table("trips")
    op.drop_table("truck_utilization_metrics")
    op.drop_index(op.f("ix_maintenance_records_truck_id"), table_name="maintenance_records")
    op.drop_table("maintenance_records")
    op.drop_index(op.f("ix_loads_route_id"), table_name="loads")
    op.drop_index("ix_loads_load_status", table_name="loads")
    op.drop_index("ix_loads_load_date", table_name="loads")
    op.drop_index(op.f("ix_loads_customer_id"), table_name="loads")
    op.drop_table("loads")
    op.drop_table("driver_monthly_metrics")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_trucks_status", table_name="trucks")
    op.drop_table("trucks")
    op.drop_index("ix_trailers_status", table_name="trailers")
    op.drop_table("trailers")
    op.drop_table("routes")
    op.drop_table("facilities")
    op.drop_index("ix_drivers_employment_status", table_name="drivers")
    op.drop_table("drivers")
    op.drop_table("customers")
    # ### end Alembic commands ###
