from src.models import (
    Base,
    Customer,
    DeliveryEvent,
    Driver,
    DriverMonthlyMetrics,
    Facility,
    FuelPurchase,
    Load,
    MaintenanceRecord,
    Route,
    SafetyIncident,
    Trailer,
    Trip,
    Truck,
    TruckUtilizationMetrics,
)

DOMAIN_TABLES: dict[str, type[Base]] = {
    "drivers": Driver,
    "trucks": Truck,
    "trailers": Trailer,
    "customers": Customer,
    "facilities": Facility,
    "routes": Route,
    "loads": Load,
    "trips": Trip,
    "fuel_purchases": FuelPurchase,
    "maintenance_records": MaintenanceRecord,
    "delivery_events": DeliveryEvent,
    "safety_incidents": SafetyIncident,
    "driver_monthly_metrics": DriverMonthlyMetrics,
    "truck_utilization_metrics": TruckUtilizationMetrics,
}
